### ISSUE TITLE
Everything works but the chatpad

### ISSUE THREAD

**Issue by GoogleCodeExporter** [KytechN24/xbox360wirelesschatpad#63]
```
What steps will reproduce the problem?
1.connect controller successfully through vjoy, with libusb drivers installed
2.switch mouse mode on or off
3.try typing on the chatpad

What is the expected output? What do you see instead?
text to go into text boxes, but nothing happens

What version of the product are you using? On what operating system?
Revision 30

Please provide any additional information below.
Using Windows 8.1, 3rd part wireless receiver and chatpad.

```

Original issue reported on code.google.com by `batmanz5...@gmail.com` on 11 Feb 2015 at 7:26

**Comment by KytechN24** [comment]
It sounds like a lower-level issue with how the USB packets are being transmitted between the chatpad and the wireless receiver. You could try reinstalling the libUSB driver and see if that helps. 3rd party receivers don't always send the data packets in the same format as the Microsoft receivers do, and there really isn't anything I can do about it without nearly rewriting the program completely. There's so many 3rd party brands that I can't support them all, and this program was built for Microsoft-branded receivers. There's not really anything I can do about this issue if reinstalling the libUSB drivers doesn't fix the issue.

You would either have to obtain a Microsoft-branded Xbox 360 wireless receiver and use this program, or if you are on Windows 10, you have the option to get the Xbox One wireless controller and chatpad, which supports Windows 10 out of the box [(see this page).](https://support.xbox.com/en-US/xbox-one/accessories/xbox-one-chatpad-info) These are currently your only options to have a working wireless chatpad on Windows.
