### ISSUE TITLE
Main Page Readme (Archived)

### ISSUE THREAD

**Issue by rellimmot** [KytechN24/xbox360wirelesschatpad#67]
Archived version of readme page (I could not find it on this Github page):

This application will allow you to use your Xbox 360 Wireless Controllers + Attached Chatpads on a Windows PC cordless through an Xbox 360 Wireless Receiver. Its been tested on Windows XP and Windows 7 64-Bit with decent success.

Special Thanks to Ryan and Brandon who's source code this project is based on.

Disclaimer: As this is free, open-source software I hold no liability for any damages it may cause to you or your equipment. There isn't too much being installed, and I believe everything can be un-done but, use at your own risk. See the Readme.txt inside the archive for more details.

Latest Version: Revision 30

Cleaned up a good amount of extraneous I/O traffic with the chatpad. This should help reduce any random disconnect problems or missed key presses when the host computer is running something intensive like an MMO. Also fixed a bug where Mouse Mode was not being remembered properly.
Previous Updates

Fixed issue with controller connection and multiple navigation shortcuts executing.
Updated with closer Xbox button mappings. Hopefully this help until custom button mapings can be implemented (soon-ish)
Added Mouse Mode to be remembered as a setting over multiple launches.
Added LED indicators for Mouse Mode. Green LED when Mouse Mode turns On, Red LED when Mouse Mode turns Off.
Reversed direction of Log messages in the textbox.
Fixed an issue where Ctrl1 Trigger As Button was not being remembered properly.
New Feature: Special Command - Disable Controller by holding down Left Trigger + Right Trigger + Back for more than 5 seconds.
New Feature: Special Command - Toggle Mouse Mode by holding down Left Bumper + Right Bumper + Back for more than 3 seconds. See below for further details.
Added Multiple Controller Support. This is preliminary and is VERY difficult for me to test properly with the lack of controllers. I make no guarantees that it will work flawlessly but please open an issue if you're having problems. For multiple controllers to work you must have multiple vJoy devices configured using the vJoyConf utility like described below. There is a counter on the bottom right of the utility you can increment to specify additional devices.
Changed FFXIV Compatibility mode to Trigger As Button mode. The biggest difference the compatibility mode did was make the left and right triggers react as normal buttons instead of a full ranged axis. This was necessary for FFXIV to properly address them. Note that the non-FFXIV button mapping no longer exist as an option without compiling the source individually. I'm looking into making the customization more flexible (there has been much outcry over it) but it will take some time.
Massive reorganization and cleanup of the code and SVN repository as a whole.
Attempted having the application create the vJoy configuration, skipping a full install step. However this will take a bit more time.
Known Functional Limitations

-The native XInput driver is replaced with a non XInput driver. This may cause issue when using the controller in newer games that are expecting XInput functionality.

-Headset not supported. The scope of this application is not to create a driver but drive existing drivers (vJoy). To implement this I would need to find a virtual audio driver or create my own, and it may not work great due to latency issues anyway. Also, because this is windows, there are many ways to attach a headset/microphone other than through the Xbox 360 Controller. In short, I don't see a huge need for this functionality, but feel free to post an issue if you'd really like to see it added. With enough support, I may try to explore it.

-Force Feedback not supported. This could be quite difficult to implement, I know how to tell the controller to rumble, but the vJoy device does not have a force feedback status. The result, I cannot determine when a game is commanding a rumble.

Installation Directions
There's a unique method of getting this driver to work which requires two other applications to be installed. Follow these installation instructions exactly before submitting any issues.

Installing the LibUSB Driver

Plug-In and Install the Native Drivers for your XBOX 360 Wireless Receiver.
Download LibUSB here. (v1.2.6)
Extract the Archive to a Directory.
Execute the following as an Admin: Directory/bin/Architecture/install-filter-win.exe
Select "Install a Device Filter".
Select the item with Description "Xbox 360 Wireless Receiver for Windows".
Select "Install" then after the confirmation box select Cancel.
Execute the following path: Directory/bin/inf-wizard.exe
Select "Next".
Select the item with Description "Xbox 360 Wireless Receiver for Windows".
Select "Next" then save the new .inf somewhere.
Select "Install Now" to install the driver.
Select OK at the confirmation, the LibUSB driver should now be installed.
Installing the vJoy Driver

Download vJoy here. (v2.0.2)
Install as an Admin with at least the vJoy Configuration Application.
Run "Configure vJoy" from the newly created Start Menu folder.
Match the following selection then hit OK:
Basic Axes Selected: X, Y, Z, R/Rz/Rudder
Additional Axes Selected: Rx, Ry
POV Hat Switch: Continuous
POVs: 1
Number of Buttons: 11
The Configuration utility will disappear, the vJoy Driver should now be installed.
Note: For multiple controller support you can specify additional configurations with this utility. Use the counter in the bottom right of the program to change between 1, 2, 3, and 4 controllers.
Running the Xbox 360 Wireless Chatpad Application

Download the latest version of the application here.
Extract all of the files in the archive to a single directory.
Execute "Xbox 360 Wireless Chatpad.exe"
Follow in instruction in the application to connect your controller.
Note: The first time you connect a controller, you should Calibrate it using the Windows Game Controllers utility in the Control Panel (Windows XP). The following describes different Axes during calibration (Xbox Stick: Windows Name)

Left Stick: Primary Axis
Left Trigger: Z Axis
Right Trigger: Z Rotation
Right Stick X: X Rotation
Right Stick Y: Y Rotation
Final Fantasy XIV Users
In order to use the Final Fantasy XIV compatibility mode, the vJoystick should be configured with the following settings instead of above:

Basic Axes Selected: X, Y, Z, R/Rz/Rudder
POV Hat Switch: Continuous
POVs: 1
Number of Buttons: 13
It is fine if you've already configured above, just re-run the utility and use these settings. Afterwards, launch the program like normal but before selection the Connect Controller button, check the Final Fantasy XIV box. After connecting, calibrate like normal in Windows, then you "should" be good to go in Final Fantasy XIV. In-game, you'll definitely want to check the controller calibration options to validate the settings are working properly.
Special Commands
Mouse Mode will allow you to move the mouse cursor, perform both left and right clicks, and scroll a window vertically. To enable Mouse Mode simply hold down the following button combination for 3 seconds:

Left Bumper + Right Bumper + Back
Once in Mouse Mode use the left stick to move the mouse cursor. Holding down the Left Trigger will scale how fast the cursor moves. Use the A Button for Left Click and B Button for Right Click. Use the Right Joystick Y Axis to scroll a window vertically, similar to a mouse wheel.
To shut down a controller while leaving the application running hold down the following button combination for 5 seconds:

Left Trigger + Right Trigger + Back
To reconnect the controller, simply press the Guide button like normal.

**Comment by KytechN24** [comment]
I just found the readme for the project in the wiki branch. I will be getting that put up soon.
